MistoonAnime:
  base: ""
  path: "models/Diffusion_Models/mistoonAnime.safetensors"
  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"
    - "models/Motion_Module/mm_sd_v15.ckpt"

  seed:           [16372571278361863751]
  steps:          25
  guidance_scale: 8.5

  prompt:
    - "masterpiece, best quality, 1girl, solo, cherry blossoms, hanami, pink flower, white flower, spring season, falling petals, white hair, black eyes"

  n_prompt:
    - "watermark, text, words, bad quality"

